"""your message

Revision ID: ffdb7f53eb16
Revises: 71b3fa796efa
Create Date: 2024-07-04 14:27:01.574608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdb7f53eb16'
down_revision = '71b3fa796efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
